### ISSUE TITLE
Cannot read field "allEntities" because "into" is null 	

### ISSUE THREAD

**Issue by starmc63** [LuminolMC/LightingLuminol#4]
### 服务端版本 LightingLuminolMC Version

git-Luminol-"811b626"

### 预期的行为 Expected behavior

2],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=24,hash=110880607},RegionSection{sectionCoordinate=[-2, 1],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=19,hash=2012670052},RegionSection{sectionCoordinate=[5, -12],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=2,hash=833242414},RegionSection{sectionCoordinate=[4, -11],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=1,hash=1797121107},RegionSection{sectionCoordinate=[7, -13],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=3,hash=1835440272},RegionSection{sectionCoordinate=[1, -6],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=5,hash=882781052},RegionSection{sectionCoordinate=[6, 6],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=2,hash=1953189955},RegionSection{sectionCoordinate=[0, 5],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=10,hash=1892687329},RegionSection{sectionCoordinate=[-1, 5],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=10,hash=690731379},RegionSection{sectionCoordinate=[0, -5],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=10,hash=1814799073},RegionSection{sectionCoordinate=[-5, 6],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=1,hash=1122766447},RegionSection{sectionCoordinate=[7, 5],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=2,hash=849554630},RegionSection{sectionCoordinate=[14, 0],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=2,hash=1186458560},RegionSection{sectionCoordinate=[1, -1],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=24,hash=2008704349},RegionSection{sectionCoordinate=[-1, 0],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=24,hash=1426559667},RegionSection{sectionCoordinate=[-3, -4],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=8,hash=2129220041},RegionSection{sectionCoordinate=[3, 3],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=19,hash=125389887},RegionSection{sectionCoordinate=[7, 0],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=5,hash=600654080},RegionSection{sectionCoordinate=[13, -1],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=2,hash=1253494208},RegionSection{sectionCoordinate=[8, -12],chunkCount=12,chunksBitset=000000000000bf79,nonEmptyNeighbours=2,hash=2120596038},RegionSection{sectionCoordinate=[7, -14],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=2,hash=858786049},RegionSection{sectionCoordinate=[6, -13],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=2,hash=2050792230},RegionSection{sectionCoordinate=[9, -11],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=1,hash=102269292}]}
java.lang.NullPointerException: Cannot read field "allEntities" because "into" is null
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:184) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:75) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:299) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:831) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:663) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:987) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:417) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:443) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:20:06] [Region Scheduler Thread #9/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Uncaught exception in tick thread "Region Scheduler Thread #9"
java.lang.NullPointerException: Cannot read field "allEntities" because "into" is null
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:184) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:75) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:299) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:831) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:663) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:987) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:417) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:443) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### 观测到的实际行为 Observed/Actual behavior

2],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=24,hash=110880607},RegionSection{sectionCoordinate=[-2, 1],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=19,hash=2012670052},RegionSection{sectionCoordinate=[5, -12],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=2,hash=833242414},RegionSection{sectionCoordinate=[4, -11],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=1,hash=1797121107},RegionSection{sectionCoordinate=[7, -13],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=3,hash=1835440272},RegionSection{sectionCoordinate=[1, -6],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=5,hash=882781052},RegionSection{sectionCoordinate=[6, 6],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=2,hash=1953189955},RegionSection{sectionCoordinate=[0, 5],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=10,hash=1892687329},RegionSection{sectionCoordinate=[-1, 5],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=10,hash=690731379},RegionSection{sectionCoordinate=[0, -5],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=10,hash=1814799073},RegionSection{sectionCoordinate=[-5, 6],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=1,hash=1122766447},RegionSection{sectionCoordinate=[7, 5],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=2,hash=849554630},RegionSection{sectionCoordinate=[14, 0],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=2,hash=1186458560},RegionSection{sectionCoordinate=[1, -1],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=24,hash=2008704349},RegionSection{sectionCoordinate=[-1, 0],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=24,hash=1426559667},RegionSection{sectionCoordinate=[-3, -4],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=8,hash=2129220041},RegionSection{sectionCoordinate=[3, 3],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=19,hash=125389887},RegionSection{sectionCoordinate=[7, 0],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=5,hash=600654080},RegionSection{sectionCoordinate=[13, -1],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=2,hash=1253494208},RegionSection{sectionCoordinate=[8, -12],chunkCount=12,chunksBitset=000000000000bf79,nonEmptyNeighbours=2,hash=2120596038},RegionSection{sectionCoordinate=[7, -14],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=2,hash=858786049},RegionSection{sectionCoordinate=[6, -13],chunkCount=16,chunksBitset=000000000000ffff,nonEmptyNeighbours=2,hash=2050792230},RegionSection{sectionCoordinate=[9, -11],chunkCount=0,chunksBitset=0000000000000000,nonEmptyNeighbours=1,hash=102269292}]}
java.lang.NullPointerException: Cannot read field "allEntities" because "into" is null
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:184) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:75) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:299) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:831) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:663) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:987) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:417) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:443) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:20:06] [Region Scheduler Thread #9/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Uncaught exception in tick thread "Region Scheduler Thread #9"
java.lang.NullPointerException: Cannot read field "allEntities" because "into" is null
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:184) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:75) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:299) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:831) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:663) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:987) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:417) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:443) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[lightingluminol-1.20.4.jar:git-Luminol-"1314604"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### 复现步骤 Steps/models to reproduce

未知

### 插件与数据包列表。 Plugin and Datapack List.

ArmorStandEditor, BetterRTP, BlockLocker, ChatFormatter, ChunkRegenerator, ContainerCheck, CoreProtect, Craftorithm, CreeperFireworks, CSpeak
[22:00:39 INFO]:  CustomJoinMessage, DeathMessageLimiter, Essentials, EssentialsSpawn, FancyHolograms, FirstJoinBook, FramedImage, FreedomChat, GSit, Log10Damage
[22:00:39 INFO]:  LuckPerms, MiniMOTD, Multiverse-Core, NoBindingCurse, NoBreakFrame, NoJoinMessage, PhantomIsolation2, PlaceholderAPI, PlasmoVoice, PlayerParticles
[22:00:39 INFO]:  PlayerTitle, PlugManX, PrivateItem, PrivateMap, ProtocolLib, QuickShop-Hikari, RayTraceAntiXray, SkinsRestorer, Slimefun, TAB
[22:00:39 INFO]:  Terra, Titles, Towny, TownyFlight, TownyMenus, UltimateShop, Vault, ViaBackwards, ViaVersion, Visible
[22:00:39 INFO]:  VisualItem

**Comment by s-j-y-m** [comment]
有没有佬解释下这个BUG会导致什么问题
